### ISSUE TITLE
Usage of epoch variable instead of T_cur

### ISSUE THREAD

**Issue by bhalajin** [4uiiurz1/keras-cosine-annealing#1]
As per my understanding of the paper, the authors use **'Tcur'** which denotes the number of epochs since the last restart. But I see that you have used epoch instead of it.

**Is there any specific reason for using epoch directly?** 

I see that the epochs in the upward cosine curve don't make any significant impact on the scheduler. Instead, once the eta_min is reached, the Tcur variable could be restarted.

**Comment by 4uiiurz1** [comment]
I have only implemented the cosine annealing part of SGDR, and not the restarts, because restarts is almost never used in several papers.

**Comment by bhalajin** [comment]
@4uiiurz1, Thanks for your quick response.
I have forked your repo to implement restart and also to add T_multi functionality.
